'use client'

import Link from 'next/link'
import { BriefcaseBusiness, Camera, Globe2, Heart, Menu, MessageCircle, Search, ShoppingBag, Star, X } from 'lucide-react'
import { useState } from 'react'
import type { Product } from '@/lib/catalog'
import { formatPrice } from '@/lib/catalog'
import { useCart, useWishlist } from '@/hooks/use-store'

export function Header() { const [open, setOpen] = useState(false); const { count } = useCart(); return <><div className="utility-bar">PRINTKART24 — made for your next big idea. <span>Free delivery on orders over ₹999</span></div><header className="site-header"><div className="page-shell header-row"><button className="icon-button mobile-only" onClick={() => setOpen(true)} aria-label="Open menu"><Menu size={21}/></button><Link href="/" className="brand-mark"><span>PRINT</span><i>KART24</i><b>®</b></Link><form action="/search" className="search-box header-search"><Search size={18}/><input name="q" placeholder="Search for products or designs" aria-label="Search products"/><button type="submit" aria-label="Submit search"><Search size={18}/></button></form><div className="header-actions"><Link href="/login" className="header-signin">Sign in</Link><Link href="/wishlist" className="icon-button" aria-label="Wishlist"><Heart size={20}/></Link><Link href="/cart" className="bag-button" aria-label={`Cart with ${count} items`}><ShoppingBag size={20}/><span>{count}</span></Link></div></div><div className="page-shell category-nav"><nav><Link href="/category/business-printing">Products</Link><Link href="/category/photo-gifts">Design services</Link><Link href="/category/business-printing">Marketing services</Link><Link href="/category/stationery">Resources</Link><Link href="/category/photo-gifts">Inspiration</Link><Link href="/category/business-printing">Deals</Link><Link href="/contact">Help</Link></nav></div></header>{open && <div className="mobile-drawer"><div className="drawer-scrim" onClick={() => setOpen(false)}/><aside><div className="drawer-top"><span className="brand-mark"><span>PRINT</span><i>KART</i><b>®</b></span><button className="icon-button" onClick={() => setOpen(false)} aria-label="Close menu"><X size={21}/></button></div><nav><Link href="/" onClick={() => setOpen(false)}>Home</Link><Link href="/category/business-printing" onClick={() => setOpen(false)}>Business printing</Link><Link href="/category/photo-gifts" onClick={() => setOpen(false)}>Photo gifts</Link><Link href="/category/clothing" onClick={() => setOpen(false)}>Clothing</Link><Link href="/category/stationery" onClick={() => setOpen(false)}>Stationery</Link></nav></aside></div>}</> }

export function Footer() { return <footer className="footer"><div className="page-shell"><div className="footer-reference-brand"><div className="brand-mark footer-brand"><span>PRINT</span><i>KART24</i><b>®</b></div><div className="footer-rule"/></div><div className="footer-top"><div><strong>About</strong><Link href="/about">Our story</Link><Link href="/contact">Press & contact</Link><Link href="/about">Careers</Link><Link href="/about">Our responsibility</Link></div><div><strong>Account</strong><Link href="/login">Sign in</Link><Link href="/register">Create account</Link><Link href="/orders">Track my order</Link><Link href="/shipping">Return policy</Link></div><div><strong>For creators</strong><Link href="/contact">Sell with PRINTKART24</Link><Link href="/contact">Creator program</Link><Link href="/faq">Guidelines</Link><Link href="/contact">Help</Link></div><div><strong>Explore</strong><Link href="/category/photo-gifts">Gifts & occasions</Link><Link href="/category/business-printing">Business printing</Link><Link href="/category/stationery">Ideas</Link><Link href="/contact">Support</Link></div></div><div className="footer-social"><a href="https://facebook.com/printkart24" target="_blank" rel="noreferrer" aria-label="Facebook"><Globe2 size={22}/></a><a href="https://instagram.com/printkart24" target="_blank" rel="noreferrer" aria-label="Instagram"><Camera size={22}/></a><a href="https://linkedin.com/company/printkart24" target="_blank" rel="noreferrer" aria-label="LinkedIn"><BriefcaseBusiness size={22}/></a><a href="tel:+918288811860" aria-label="Call PRINTKART24"><span className="footer-phone">+91 82888 11860</span></a></div><div className="footer-bottom"><span>© 2026 PRINTKART24. Made with intent.</span><span>Privacy · Terms · India</span></div></div></footer> }

export function WhatsAppButton() { const href = 'https://wa.me/918288811860?text=Hi%20PRINTKART%2C%20I%20need%20help%20with%20my%20order.'; return <a className="whatsapp-fab" href={href} target="_blank" rel="noreferrer" aria-label="Chat with PRINTKART24 on WhatsApp"><MessageCircle size={20} fill="currentColor" /><span>Chat with us</span></a> }

export function Rating({ rating, reviews }: { rating: number; reviews: number }) { return <span className="rating"><Star size={14} fill="currentColor"/> {rating} <small>({reviews})</small></span> }

export function ProductCard({ product }: { product: Product }) { const [wishlist, setWishlist] = useWishlist(); const saved = wishlist.includes(product.slug); return <article className="catalog-card"><Link href={`/product/${product.slug}`} className="catalog-image"><img src={product.image} alt={product.name}/>{product.badge && <span className="product-badge">{product.badge}</span>}<button type="button" className={`favorite-button ${saved ? 'is-favorite' : ''}`} aria-label={`Save ${product.name}`} onClick={(event) => { event.preventDefault(); setWishlist(saved ? wishlist.filter((item) => item !== product.slug) : [...wishlist, product.slug]) }}><Heart size={18} fill={saved ? 'currentColor' : 'none'}/></button></Link><div className="catalog-info"><Link href={`/product/${product.slug}`}><h3>{product.name}</h3></Link><Rating rating={product.rating} reviews={product.reviews}/><div><strong>{formatPrice(product.price)}</strong>{product.originalPrice && <del>{formatPrice(product.originalPrice)}</del>}<small> onwards</small></div></div></article> }

export function ProductGrid({ products }: { products: Product[] }) { return <div className="catalog-grid">{products.map((product) => <ProductCard product={product} key={product.slug}/>)}</div> }
